#!/usr/bin/env bash
echo Insert username:
read user
echo Insert password:
read -s pass
sudo mysql -u${user} -p${pass} <<EOF
CREATE DATABASE IF NOT EXISTS userdata;
USE userdata;
CREATE TABLE IF NOT EXISTS users (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, username VARCHAR(64) NOT NULL, password VARCHAR(255) NOT NULL, salt BINARY(64) NOT NULL, role VARCHAR(10), UNIQUE(username));
CREATE USER IF NOT EXISTS credentialsMusicApp IDENTIFIED BY 'validate';
GRANT SELECT, INSERT ON userdata.users TO credentialsMusicApp;
EOF
